Update 026-1b0470z0012j.yaml
Did a bunch of testing and found that setting any values on the fridge do not work. Also unclear what both work_mode properties do. I tested multi unit support but then comparing min and max values breaks in ha (tested in 2025.5.2)
TypeError: '<' not supported between instances of 'float' and 'dict'
So I concentrated on the sensor properties first.